Run all tests, then fail make if required
git-svn-id: https://svn.apache.org/repos/asf/apr/apr/trunk@574134 13f79535-47bb-0310-9956-ffa450edef68

diff --git a/test/Makefile.in b/test/Makefile.in
--- a/test/Makefile.in
+++ b/test/Makefile.in
@@ -45,15 +45,20 @@ INCLUDES=-I$(INCDIR) -I$(srcdir)/../include
 LINK_PROG = $(LIBTOOL) $(LTFLAGS) --mode=link $(LT_LDFLAGS) $(COMPILE) @LT_NO_INSTALL@ $(ALL_LDFLAGS) -o $@
 
 check: $(STDTEST_PORTABLE) $(STDTEST_NONPORTABLE)
+	teststatus=0; \
+	progfailed=""; \
 	for prog in $(STDTEST_PORTABLE) $(STDTEST_NONPORTABLE); do \
 		./$$prog; \
 		status=$$?; \
 		if test $$status != 0; then \
-			echo "$$prog failed"; \
-			break; \
+			teststatus=$$status; \
+			progfailed="$$progfailed $$prog"; \
 		fi; \
 	done; \
-	exit $$status
+	if test $$teststatus != 0; then \
+		echo "Programs failed:$$progfailed"; \
+	fi; \
+	exit $$teststatus
 
 occhild@EXEEXT@: occhild.lo $(LOCAL_LIBS)
 	$(LINK_PROG) occhild.lo $(LOCAL_LIBS) $(ALL_LIBS)
